The dataset is GEMEP and the path is ../datasets/GEMEP/
Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    eps: 1e-08
    lr: 0.001
    weight_decay: 0.01
)
  0%|                                                                                       | 0/100 [00:00<?, ?it/s]
[Epoch 1] Training accuracy: 0.6906. Loss: 0.907 LR: 0.001000

  1%|▊                                                                              | 1/100 [00:27<45:49, 27.77s/it]
[Epoch 1] Validation accuracy:0.3322. Loss:2.561
Val correct sum 469 and length is 1412
best_acc:0.3322
[Epoch 2] Training accuracy: 0.8707. Loss: 0.418 LR: 0.001000

  2%|█▌                                                                             | 2/100 [00:54<43:54, 26.88s/it]
[Epoch 2] Validation accuracy:0.3824. Loss:2.572
Val correct sum 540 and length is 1412
best_acc:0.3824
[Epoch 3] Training accuracy: 0.9136. Loss: 0.274 LR: 0.001000
Training correct sum 5159 and length is 5647
[Epoch 3] Validation accuracy:0.6006. Loss:1.600
  2%|█▌                                                                           | 2/100 [01:19<1:05:14, 39.94s/it]
Traceback (most recent call last):
  File "train_hfp.py", line 254, in <module>
    main()
  File "train_hfp.py", line 127, in main
    store_weight(i, model.state_dict(), optimizer.state_dict(), val_acc, fold)
  File "train_hfp.py", line 220, in store_weight
    torch.save({'iter': epoch,
  File "C:\Users\Ho Ping-Hsueh\Anaconda3\envs\test\lib\site-packages\torch\serialization.py", line 369, in save
    with _open_file_like(f, 'wb') as opened_file:
  File "C:\Users\Ho Ping-Hsueh\Anaconda3\envs\test\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Users\Ho Ping-Hsueh\Anaconda3\envs\test\lib\site-packages\torch\serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '../models\\GEMEP\\split\\0\\_epoch3_acc0.6006.pth'