Loading pretrained weights... ../models/GEMEP/epoch3_acc0.533.pth
The dataset is GEMEP and the path is ../datasets/GEMEP/
Train set size: 5740
Validation set size: 1319
Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    eps: 1e-08
    lr: 0.01
    weight_decay: 0.0001
)
  0%|                                                                                       | 0/200 [00:00<?, ?it/s]
[Epoch 1] Training accuracy: 0.3380. Loss: 1.798 LR: 0.010000
Training correct sum 1940 and length is 5740
[Epoch 1] Validation accuracy:0.1766. Loss:1.963
Val correct sum 233 and length is 1319

  0%|▍                                                                            | 1/200 [00:49<2:43:37, 49.34s/it]
Traceback (most recent call last):
  File "train_hfp.py", line 242, in <module>
    main()
  File "train_hfp.py", line 107, in main
    train(i, train_loader, len_train, model, CE_criterion, optimizer, scheduler)
  File "train_hfp.py", line 127, in train
    for batch_i, (imgs, targets, _) in enumerate(train_loader):
  File "C:\Users\Ho Ping-Hsueh\Anaconda3\envs\test\lib\site-packages\torch\utils\data\dataloader.py", line 435, in __next__
    data = self._next_data()
  File "C:\Users\Ho Ping-Hsueh\Anaconda3\envs\test\lib\site-packages\torch\utils\data\dataloader.py", line 1068, in _next_data
    idx, data = self._get_data()
  File "C:\Users\Ho Ping-Hsueh\Anaconda3\envs\test\lib\site-packages\torch\utils\data\dataloader.py", line 1024, in _get_data
    success, data = self._try_get_data()
  File "C:\Users\Ho Ping-Hsueh\Anaconda3\envs\test\lib\site-packages\torch\utils\data\dataloader.py", line 872, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "C:\Users\Ho Ping-Hsueh\Anaconda3\envs\test\lib\queue.py", line 179, in get
    self.not_empty.wait(remaining)
  File "C:\Users\Ho Ping-Hsueh\Anaconda3\envs\test\lib\threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt